// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vvvjvjrxzneilydevcbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZ2dmp2anJ4em5laWx5ZGV2Y2JlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUwNjU5NzgsImV4cCI6MjA2MDY0MTk3OH0.FMhWwvQOe0io8E4kAYbKK-E0rhRR7DLxjfgQqXTwFhs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);